name: Complete Enterprise Pipeline

on:
  push:
    branches:
      - main
      - feature/*
  workflow_dispatch:

env:
  APP_NAME: enterprise-app
  VERSION: "1.0"

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      run:echo "Hello, world"
